### ISSUE TITLE
Replace fonts source for privacy

### ISSUE THREAD

**Issue by landergate** [IceWreck/Argon-Dokuwiki-Template#1]
Usage of fonts.googleapis.com results in "Referer" header being sent containing article URL. This could lower privacy on private wikis.

Other resources are being loaded locally. Doing the same with Open Sans could make sense.

**Comment by IceWreck** [comment]
Thanks ! Fixed it in 7eeced9ec59d897acd04c212a925e94d5d0c4190
Will publish an update soon.
