### ISSUE TITLE
Cannot modify header information warning

### ISSUE THREAD

**Issue by rk** [IceWreck/Argon-Dokuwiki-Template#12]
```
Warning: Cannot modify header information
 - headers already sent by (output started 
at lib/tpl/argon/main.php:1) in 
lib/tpl/argon/main.php on line 15
```

https://github.com/IceWreck/Argon-Dokuwiki-Template/blob/1fd9dbd05721ea0c6e77ca535bc376329eb55eee/main.php#L1-L9

This HTML comment forces headers to be written, before they’re supposed to be on line 15. Maybe you could just move it to a PHP comment in the opening tag, or immediately before the opening `<html>` tag?

**Comment by IceWreck** [comment]
> This HTML comment forces headers to be written, before they’re supposed to be on line 15. Maybe you could just move it to a PHP comment in the opening tag,

Will do. Thanks.
