### ISSUE TITLE
PHP Warning: Warning: Cannot modify header information

### ISSUE THREAD

**Issue by tanrak** [IceWreck/Argon-Dokuwiki-Template#3]
Hi, first nice theme, but i have a php warning:

`Warning: Cannot modify header information - headers already sent by (output started at /somefolders/wiki/lib/tpl/argon/main.php:1) in /somefolders/wiki/lib/tpl/argon/main.php on line 15`

If i commented out this line the warning is gone. Is this row necessary?

**Comment by IceWreck** [comment]
> Is this row necessary?

`header('X-UA-Compatible: IE=edge,chrome=1');`

I don't think so. Feel free to remove it. Its probably leftover code from the base template that needs to be removed.

**Comment by mariohommel** [comment]
In case you want to keep that line you can delete all lines on top of the main.php file so that the "<?php" line is the first in file. This will also pretend the warning message.

**Comment by tanrak** [comment]
OK. Thanks for the info. I will close the issue.
