### ISSUE TITLE
Plugin compatibility. Adding class="dokuwiki" at the leading div

### ISSUE THREAD

**Issue by ShrinkWrapper** [IceWreck/Argon-Dokuwiki-Template#4]
Some plugins use the .dokuwiki class to apply css.
One of them being the [Wrap plugin](https://www.dokuwiki.org/plugin:wrap) 
Its currently not working together with the Argon template.
I tested adding .dokuwiki to the body class in main.php and that seemed to fix it.
![image](https://user-images.githubusercontent.com/2026662/79387021-4be8d600-7f6b-11ea-8c43-6c64b6751a81.png)

There might be a better way to go about this, but that's at least a quick fix.

Edit: It seems to break some other parts of the site, login box being one.

**Comment by IceWreck** [comment]
Thanks. I'll take a look and try to fix it.

**Comment by IceWreck** [comment]
Yes, I forgot to include the dokuwiki class. It should be added in the <main> tag but it will break parts of the site because I wrote css around it.  Only way to fix it is to fix that css. Will do that this week.

**Comment by ShrinkWrapper** [comment]
Nice, much appreciated! 👍

**Comment by IceWreck** [comment]
Its mostly implemented. I fixed other things that it broke, but still need to make the login screen prettier

**Comment by ShrinkWrapper** [comment]
Thanks for the new update, looks good!
