### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by codewithelvin** [IceWreck/Argon-Dokuwiki-Template#5]
```Warning: Cannot modify header information - headers already sent by (output started at /shared/httpd/dokuwiki/htdocs/lib/tpl/argon/main.php:1) in /shared/httpd/dokuwiki/htdocs/lib/tpl/argon/main.php on line 15```

**Comment by IceWreck** [comment]
This was fixed recently, the fix will be out in another update soon

**Comment by codewithelvin** [comment]
OK. I close issue and will update template.
