### ISSUE TITLE
Extraneous whitespace in title

### ISSUE THREAD

**Issue by alexforencich** [IceWreck/Argon-Dokuwiki-Template#8]
There is extraneous whitespace in the title tag that results in the opening bracket being separated from the wiki name, some this:

Page Name [ Wiki Name]

instead of

Page Name [Wiki Name]

The culprit appears to be here: https://github.com/IceWreck/Argon-Dokuwiki-Template/blob/master/main.php#L28

**Comment by IceWreck** [comment]
Thanks! Fixed.
